### ISSUE TITLE
Init config fails on CLI

### ISSUE THREAD

**Issue by flobaader** [rigdev/rig#495]
#### Describe the bug

Its currently not possible to init the config on macos.

#### Expected behavior

The init process, as documented in the docs should start.

#### Logs

Output when running `rig config init`

```
Error: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/config".initCmd (/home/runner/work/rig/rig/cmd/rig/cmd/config/setup.go:23): failed to build rig.Client: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func1 (/home/runner/work/rig/rig/cmd/rig/cmd/base/client.go:33): failed to build *cmdconfig.Service: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func5 (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:25): failed to build *cmdconfig.Context: received non-nil error from function "github.com/rigdev/rig/cmd/rig/cmd/base".getContext (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:37): no current context in config, run `rig config init`
Usage:
  rig config init [flags]

Flags:
  -h, --help   help for init

Global Flags:
  -e, --environment string    (default "default")
  -o, --output OutputType    output type. One of json,yaml,pretty. (default pretty)

2024/01/16 09:46:22 could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/config".initCmd (/home/runner/work/rig/rig/cmd/rig/cmd/config/setup.go:23): failed to build rig.Client: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func1 (/home/runner/work/rig/rig/cmd/rig/cmd/base/client.go:33): failed to build *cmdconfig.Service: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func5 (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:25): failed to build *cmdconfig.Context: received non-nil error from function "github.com/rigdev/rig/cmd/rig/cmd/base".getContext (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:37): no current context in config, run `rig config init`
```

#### Additional contextual information

- OS: macOS
- Rig Version 1.5.5

**Comment by MatiasFrank** [comment]
Thanks for trying out Rig and opening the issue! The bug is fixed on main and we'll make a release in the coming days. I'll close the issue once the new release is out.

**Comment by flobaader** [comment]
Hey @MatiasFrank, just to let you know the bug still exists on v1.6.0:

```
Error: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/config".initCmd (/home/runner/work/rig/rig/cmd/rig/cmd/config/setup.go:29): failed to build rig.Client: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func1 (/home/runner/work/rig/rig/cmd/rig/cmd/base/client.go:18): failed to build *cmdconfig.Service: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func5 (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:25): failed to build *cmdconfig.Context: received non-nil error from function "github.com/rigdev/rig/cmd/rig/cmd/base".getContext (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:51): no current context in config, run `rig config init`
Usage:
  rig config init [flags]

Flags:
  -h, --help   help for init

Global Flags:
  -e, --environment string
  -o, --output OutputType    output type. One of json,yaml,pretty. (default pretty)

2024/01/18 22:00:43 could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/config".initCmd (/home/runner/work/rig/rig/cmd/rig/cmd/config/setup.go:29): failed to build rig.Client: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func1 (/home/runner/work/rig/rig/cmd/rig/cmd/base/client.go:18): failed to build *cmdconfig.Service: could not build arguments for function "github.com/rigdev/rig/cmd/rig/cmd/base".glob..func5 (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:25): failed to build *cmdconfig.Context: received non-nil error from function "github.com/rigdev/rig/cmd/rig/cmd/base".getContext (/home/runner/work/rig/rig/cmd/rig/cmd/base/register.go:51): no current context in config, run `rig config init`
```

**Comment by MatiasFrank** [comment]
I can't seem to reproduce the error on my side. Can you try and delete the rig config and try again? On linux the config is at `~/.config/rig/config.yaml` and macOS it's `~/Library/Application\ Support/rig/config.yaml`

**Comment by flobaader** [comment]
Yes that worked - thank you!
